spring:
  datasource:
    username: root
    password: 930419
    url: jdbc:mysql://localhost:3306/scw?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  config-location: classpath:/mybatis/mybatis-config.xml
#  mapper-locations: classpath:/mybatis/mapper/*.xml
#    type: com.alibaba.druid.pool.DruidDataSource